[build]
  command = "npx tailwindcss -i ./src/assets/css/main.css -o ./src/assets/css/tailwind.css --minify && PATHPREFIX=/ npx @11ty/eleventy && cp src/assets/css/tailwind.css _site/assets/css/"
  publish = "_site"
