backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "src/assets/images"
public_folder: "/assets/images"

locale: el

collections:
  - name: "posts"
    label: "Άρθρα"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "layouts/post.njk"
      - label: "Τίτλος"
        name: "title"
        widget: "string"
      - label: "Περιγραφή"
        name: "description"
        widget: "text"
      - label: "Ημερομηνία"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "DD/MM/YYYY"
        time_format: false
      - label: "Συγγραφέας"
        name: "author"
        widget: "string"
        default: "Your Name"
      - label: "Κατηγορία"
        name: "category"
        widget: "select"
        options:
          - { label: "Τεχνολογία", value: "tech" }
          - { label: "Design", value: "design" }
          - { label: "Κώδικας", value: "code" }
          - { label: "Σκέψεις", value: "thought" }
          - { label: "Ζωή", value: "life" }
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["posts"]
      - label: "Περιεχόμενο"
        name: "body"
        widget: "markdown"
